"""Repository cleanup preserves installer and legacy updater contracts."""
from pathlib import Path
import sys

from scripts import build_source_bundle as bundle
from scripts import lock_requirements as locks
from scripts import check_full_regression as regression

ROOT = Path(__file__).resolve().parents[1]


def test_reviewed_dependency_inputs_are_grouped_without_runtime_lock_moves():
    assert not list(ROOT.glob("requirements*.in"))
    assert locks.INPUTS == ROOT / "requirements"
    for name in locks.NAMES:
        assert (locks.INPUTS / (name + ".in")).is_file()
        assert (ROOT / (name + ".txt")).is_file()
        assert "--require-hashes" in (ROOT / (name + ".txt")).read_text()
    for line in (locks.INPUTS / "requirements-dev.in").read_text().splitlines():
        if line.startswith("-r "):
            assert (locks.INPUTS / line[3:]).is_file()


def test_new_input_directory_only_contains_explicit_public_inputs():
    for name in bundle.DEPENDENCY_INPUTS:
        path = Path("requirements") / name
        assert bundle.include(path, public=True)
        assert path.as_posix() in bundle.PANEL_UPDATE_EXCLUDES
    for name in ("private.in", "credentials.json", ".env", "nested/requirements.in"):
        assert not bundle.include(Path("requirements") / name, public=True)
    assert bundle.include(Path("requirements-agent.txt"), public=True)
    assert "requirements-agent.txt" not in bundle.PANEL_UPDATE_EXCLUDES


def test_lock_generator_resolves_new_inputs_and_keeps_root_outputs(monkeypatch, tmp_path):
    inputs = tmp_path / "requirements"
    inputs.mkdir()
    body = "reviewed==1.0 --hash=sha256:synthetic\n"
    header = ("# Generated by python scripts/lock_requirements.py; edit the .in inputs.\n"
              "# Universal Python >=3.13; PyPI upload cutoff 2026-09-24.\n")
    for name in locks.NAMES:
        (inputs / (name + ".in")).write_text("reviewed==1.0\n")
        (tmp_path / (name + ".txt")).write_text(header + locks.POLICY + body)
    calls = []
    def reviewed_resolver(command, **kwargs):
        source = Path(command[4])
        assert source.parent == inputs and source.is_file()
        assert kwargs["cwd"] == tmp_path
        assert "--no-build" in command
        Path(command[command.index("--output-file") + 1]).write_text(body)
        calls.append(source.name)
    monkeypatch.setattr(locks, "ROOT", tmp_path)
    monkeypatch.setattr(locks, "INPUTS", inputs)
    monkeypatch.setattr(locks.shutil, "which", lambda name: "/reviewed/uv")
    monkeypatch.setattr(locks.subprocess, "run", reviewed_resolver)
    monkeypatch.setattr(sys, "argv", ["lock_requirements.py", "--check"])
    assert locks.main() == 0
    assert calls == [name + ".in" for name in locks.NAMES]


def test_regression_fingerprint_covers_relocated_inputs(monkeypatch, tmp_path):
    source = tmp_path / "requirements" / "requirements.in"
    source.parent.mkdir()
    source.write_text("reviewed==1.0\n")
    monkeypatch.setattr(regression, "ROOT", tmp_path)
    before = regression.snapshot()
    assert "requirements/requirements.in" in before
    source.write_text("reviewed==2.0\n")
    assert regression.snapshot() != before
