"""Small authenticated channel; it does not make browser HTTP traffic private."""
from __future__ import annotations
import base64
import hashlib
import hmac
import json
import secrets
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from cryptography.hazmat.primitives.kdf.hkdf import HKDF
from cryptography.hazmat.primitives import hashes
from shared.util import valid_json_value


def token(size: int = 32) -> str:
    return secrets.token_urlsafe(size)


def digest(value: str | bytes) -> str:
    return hashlib.sha256(value.encode() if isinstance(value, str) else value).hexdigest()


def password_hash(password: str) -> str:
    salt = secrets.token_bytes(16)
    derived = hashlib.scrypt(password.encode(), salt=salt, n=16384, r=8, p=1)
    return f"scrypt$16384$8$1${salt.hex()}${derived.hex()}"


def password_verify(password: str, encoded: str) -> bool:
    try:
        _, n, r, p, salt, expected = encoded.split("$")
        derived = hashlib.scrypt(password.encode(), salt=bytes.fromhex(salt), n=int(n), r=int(r), p=int(p))
        return hmac.compare_digest(derived.hex(), expected)
    except (ValueError, TypeError):
        return False


class SecureChannel:
    """AES-256-GCM, HKDF per challenge, strict per-direction message counters.

    The long-lived key is randomly generated, never derived from a human password.
    A fresh random challenge MUST be generated by the hub on every connection.
    """
    def __init__(self, secret: str, challenge: str, device_id: str, role: str):
        if role not in {"hub", "agent"} or len(challenge) < 32 or len(secret) < 40:
            raise ValueError("Invalid channel parameters")
        key = HKDF(algorithm=hashes.SHA256(), length=32,
                   salt=challenge.encode(), info=b"remote-dev/v1/session").derive(secret.encode())
        self.cipher = AESGCM(key)
        self.prefix = f"remote-dev/v1/{device_id}/".encode()
        self.send_dir = role
        self.recv_dir = "agent" if role == "hub" else "hub"
        self.sent = 0
        self.received = 0

    def pack(self, body: dict) -> str:
        sequence = self.sent + 1
        message = {"seq": sequence, "body": body}
        if not isinstance(body, dict) or not valid_json_value(message):
            raise ValueError("Invalid channel message")
        clear = json.dumps(message, ensure_ascii=False,
                           separators=(",", ":"), allow_nan=False).encode()
        # Include nonce + GCM tag + base64 overhead before allocating ciphertext.
        if ((len(clear) + 28 + 2) // 3) * 4 > 16 * 1024 * 1024:
            raise ValueError("Packet too large")
        nonce = secrets.token_bytes(12)
        encrypted = self.cipher.encrypt(nonce, clear, self.prefix + self.send_dir.encode())
        self.sent = sequence
        return base64.b64encode(nonce + encrypted).decode()

    def unpack(self, packet: str) -> dict:
        if not isinstance(packet, (str, bytes)):
            raise ValueError("Invalid channel packet")
        if len(packet) > 16 * 1024 * 1024:
            raise ValueError("Packet too large")
        raw = base64.b64decode(packet, validate=True)
        clear = self.cipher.decrypt(raw[:12], raw[12:], self.prefix + self.recv_dir.encode())
        try:
            message = json.loads(clear)
        except (ValueError, RecursionError) as exc:
            raise ValueError("Invalid channel message") from exc
        if not isinstance(message, dict) or not valid_json_value(message):
            raise ValueError("Invalid channel message")
        if type(message.get("seq")) is not int or message["seq"] != self.received + 1:
            raise ValueError("Unexpected channel sequence")
        if not isinstance(message.get("body"), dict):
            raise ValueError("Invalid channel message")
        self.received += 1
        return message["body"]
