"""Descriptive settings index. Values and mutations remain owned by existing services.

This is not a second configuration store or a permission grant.
"""
from copy import deepcopy

GROUPS = (
    ("personal", "我的偏好与账号"),
    ("space", "空间与成员"),
    ("projects", "项目与设备"),
    ("files", "文件与产物"),
    ("development", "开发与控制"),
    ("connections", "MCP 与外部服务"),
    ("collaboration", "协作与监控"),
    ("instance", "实例与运维"),
)


def item(identifier, group, title, fields, scope, owner, source, activation, entry,
         description, risk="normal", editor=None):
    return dict(id=identifier, group=group, title=title, fields=fields.split(),
                scope=scope, owner=owner, source_kind=source, activation=activation,
                entry=entry, description=description, risk=risk, editor=editor)


CATALOG = (
    item("appearance", "personal", "全站外观", "auto light dark", "browser", "本人", "browser_storage", "immediate", "",
         "只保存于这个浏览器，其他设备不会同步。", editor="appearance"),
    item("access_defaults", "personal", "MCP 默认授权预选", "all_projects developer_scopes", "user", "本人", "database", "new_consent", "connect",
         "只预选新连接授权页面，仍需确认；关闭不会撤销已有授权，桌面控制不会默认勾选。", "security", "access_defaults"),
    item("account_security", "personal", "密码、登录身份与会话", "password identities sessions", "user", "本人 / 近期认证", "database", "immediate", "identity",
         "在账号安全入口修改。密码变更、解除身份关联可能撤销现有登录和 MCP 授权。", "security"),
    item("native_session", "personal", "CLI 会话设置", "project provider cwd model effort send_mode", "session", "有项目权限的本人", "session", "session_receipt", "native",
         "模型、思考强度、工作目录与排队方式属于具体会话；保留原生 CLI 回执，不改全局默认。"),
    item("spaces", "space", "空间与成员", "label active level blocked invitations", "space", "空间主理人 / 管理员", "database", "immediate", "members",
         "成员、邀请和空间启停由原管理入口处理；保留最后主理人保护。", "security"),
    item("roles", "space", "动态角色与委派", "enabled project_rules device_rules connector_rules may_delegate", "space", "空间管理员", "database", "new_call", "roles",
         "角色规则与资源一起校验；动态角色变化不授予面板管理员身份。", "security"),
    item("profiles", "space", "访问 Profiles", "label scopes projects all_projects enabled role_id", "user_space", "原 Profile 管理权限", "database", "new_call", "profiles",
         "Profile 只限制连接已同意的范围；保留原版本冲突校验。", "security"),
    item("sharing", "space", "记录分享", "visibility", "record", "记录所有者 / 原管理权限", "database", "immediate", "workflows",
         "私有或空间可见须在原记录中确认，不通过全局开关批量分享。", "security"),
    item("project_mapping", "projects", "项目映射", "alias device_id root description mode allow_tasks", "project", "空间管理员 / 限定新增委派", "database", "validated", "projects",
         "保存前由节点验证目录；面板写入和任务开关不能越过本机授权。", "security"),
    item("device", "projects", "设备与生命周期", "name enabled pairing update restart uninstall", "device", "设备所有者 / 空间管理员", "database", "operation_receipt", "devices",
         "设备启停、更新与重启沿用原操作回执；停用不等于所有进程已经退出。", "security"),
    item("hub_ingress", "files", "Hub 字节入站", "CODEPIER_FILE_IMPORT_STREAMING", "instance", "部署管理员", "environment", "deployment", "",
         "服务器接收受认证的有界分片，仍需目标节点与项目写入许可。"),
    item("native_relay", "files", "原生附件转发", "CODEPIER_NATIVE_FILE_RELAY", "instance", "部署管理员", "environment", "deployment", "",
         "依赖 Hub 字节入站；文件编号不是授权，来源策略单独检查。"),
    item("hub_file_sources", "files", "Hub 附件来源", "CODEPIER_NATIVE_FILE_HOSTS CODEPIER_NATIVE_FILE_PROVIDERS", "instance", "部署管理员", "environment", "deployment", "",
         "空主机列表表示明确禁止；命名 provider 未启用就保持为空。不会自动信任云存储后缀。", "security"),
    item("node_ingress", "files", "节点流式接收", "integrations.file_import_streaming", "device", "本机主理人", "agent_config", "reconnect", "integrations",
         "先选择项目并检查节点。这里不远程扩大本机授权。"),
    item("node_file_sources", "files", "节点附件来源与大小", "integrations.max_import_bytes integrations.file_hosts integrations.extra_file_hosts integrations.file_source_providers", "device", "本机主理人", "agent_config", "new_call", "integrations",
         "未设置、明确 false、空列表各有不同含义。精确主机和大小上限仍由既有来源注册表解析。", "security"),
    item("artifacts", "files", "产物、检查点与交付", "checkpoint_max_mib artifacts history", "project", "原项目权限 / 本机主理人", "agent_config", "new_call", "artifacts",
         "检查点大小仅本机配置；导出、恢复和删除是单独操作，不由默认设置代为执行。"),
    item("roots", "development", "本机目录边界", "allowed_roots.path allowed_roots.writable allowed_roots.allow_tasks", "device", "本机主理人", "agent_config", "reconnect", "devices",
         "只能在目标设备核对和修改。设置中心不展示未授权目录，也不添加读取根目录。", "security"),
    item("shell", "development", "Shell 与具名任务", "shell.enabled shell.projects shell.command shell.inherit_env shell.env shell.max_timeout_seconds tasks", "device_project", "本机主理人", "agent_config", "reconnect", "integrations",
         "Shell 使用系统账号权限，不是目录沙箱。configure --shell full 会授权全部允许项目，不能作为单项目修复。", "security"),
    item("skills", "development", "技能来源", "skills.codex_enabled skills.codex_projects skills.codex_home skills.extra_roots", "device_project", "本机主理人", "agent_config", "new_call", "integrations",
         "项目技能只读；用户技能与额外目录须本机明确选择项目，读取技能不授予执行权。", "security"),
    item("language_servers", "development", "语言服务", "integrations.language_servers.command projects enabled env settings initialization_options timeout_seconds", "device_project", "本机主理人", "agent_config", "new_session", "integrations",
         "开发工具可生成配置片段；使用 agent.setup_integrations 先预览再明确应用，不会自动安装程序。"),
    item("worktrees", "development", "隔离工作目录", "integrations.worktree_directory", "device_project", "本机主理人", "agent_config", "new_call", "integrations",
         "必须已经位于本机可写授权内；创建隔离目录不会扩大目录权限。"),
    item("browser", "development", "后台浏览器", "integrations.browser.enabled projects origins extension_id profile_id lease_seconds pool_size", "device_project", "本机主理人", "agent_config", "restart", "integrations",
         "需要扩展、档案、准确站点和空闲标签页；首次启用监听需重启，已配置不等于已连接。", "security"),
    item("computer", "development", "桌面应用控制", "computer.enabled projects allowed_apps plugin_root codex_home app_server transport max_session_seconds observation_max_age_seconds call_timeout_seconds approval_timeout_seconds", "device_project", "本机主理人 / 原生权限", "agent_config", "new_session", "devices",
         "独立于 Shell 和技能授权。只使用明确应用与项目，本机紧急停止仍有效。", "security"),
    item("local_control", "development", "本机控制接口", "integrations.local_control", "device", "本机主理人", "agent_config", "restart", "integrations",
         "首次开启本机监听需正常重启；面板项目暂停与本机接口不是同一设置。", "security"),
    item("execution_policy", "development", "MCP 执行策略", "MCP_BLOCK_LOCAL_CODEX MCP_BLOCK_NATIVE_COMPUTER mcp_policy.block_local_codex mcp_policy.block_native_computer", "instance_device", "部署管理员 / 本机主理人", "environment_agent", "new_call", "diagnostics",
         "模型/CLI 与原生桌面分别按 Hub 和 Agent 底线检查；原生策略默认允许，仍需已有 computer 授权与本机应用/项目白名单。明确禁用保留。设置中心不会修改或绕过策略，也不会授予桌面权限。", "security"),
    item("grants", "connections", "MCP 连接与授权", "scopes projects all_projects days authorization_mode profile_id role_version", "user_space", "本人 / 原授权规则", "database", "new_call", "connect",
         "固定授权、动态角色与现有连接范围在原安全入口逐项确认。", "security"),
    item("usage_privacy", "connections", "用量与隐私", "tool_text_estimate coverage historical_missing", "project", "当前项目读取权限", "database", "new_call", "integrations",
         "工具文本估算不等于宿主对话或账单 Token。历史未采集不能补算；只持久化计数，不保存凭据或完整请求内容。"),
    item("gateway", "connections", "外部 MCP 网关", "CODEPIER_MCP_GATEWAY connectors accounts bindings consent", "instance_space", "实例管理员 / 账户所有者", "database_environment", "new_call", "mcp-gateway",
         "后端凭据、精确工具发布、角色与 grant 同意均保留独立入口；不汇总凭据内容。", "security"),
    item("vps", "connections", "VPS 连接", "host port username host_key_policy enabled project_ids", "space_project", "原 VPS 管理权限", "database", "new_call", "vps",
         "连接凭据与主机校验在原安全表单管理，现有项目分配与版本校验继续有效。", "security"),
    item("oauth_policy", "connections", "OAuth 与请求来源", "MCP_ALLOWED_ORIGINS OAUTH_REDIRECT_HOSTS", "instance", "部署管理员", "environment", "deployment", "connect",
         "精确回调和请求来源是部署安全策略，不是个人偏好。", "security"),
    item("collaboration_features", "collaboration", "协作服务开关", "CODEPIER_COLLABORATION_ENABLED CODEPIER_MCP_EVENTS_ENABLED CODEPIER_MONITOR_COLLECTOR_ENABLED CODEPIER_ANALYSIS_DISPATCH_ENABLED", "instance", "部署管理员", "environment", "restart", "collaboration",
         "事件、采集器、分派依赖总开关；开启服务不授予参与者执行权限。"),
    item("collaboration_access", "collaboration", "协作参与者与发言权限", "rooms agents join_slots message_access expires", "project_environment", "已登录空间管理员", "database", "immediate", "collaboration",
         "加入码、订阅、消息权限和真实智能体绑定分别检查；订阅成功不代表模型在线。", "security"),
    item("monitor", "collaboration", "监控计划与预算", "probes rules interval_seconds valid_until maintenance budget assignee_agent_id", "project_environment", "已登录空间管理员", "database", "approved_plan", "collaboration",
         "先验证、保存，再按版本和摘要批准启用；探针恢复与分析结论分别记录。", "security"),
    item("delegation", "collaboration", "目标委派与执行边界", "participants capabilities project_ids duration budget acceptance", "project_environment", "已登录空间管理员", "database", "approved_plan", "collaboration",
         "范围、期限、步骤和消息预算属于明确授权，不能通过保存普通偏好批准执行。", "security"),
    item("public_url", "instance", "MCP 对外地址", "public_url", "instance", "实例管理员", "database_environment", "new_connection", "connect",
         "只改 MCP / OAuth 对外标识，不改监听端口、Agent 地址或人类 OIDC 回调；现有连接需重新核对授权。", "security", "public_url"),
    item("hub_process", "instance", "Hub 进程与存储", "HUB_PORT TZ HUB_DATA_DIR HUB_PUBLIC_URL MCP_PUBLIC_URL", "instance", "部署管理员", "environment", "restart", "",
         "这些值由部署管理；数据目录、监听和 OIDC 回调地址不能用 public_url 保存代替。"),
    item("reliability", "instance", "队列、等待与重试", "HUB_QUEUE_TTL_SECONDS HUB_CALL_WAIT_SECONDS HUB_DELIVERY_RETRY_SECONDS", "instance", "部署管理员", "environment", "restart", "diagnostics",
         "展示当前进程实际使用的参数；修改部署文件后须重启并重新核对。"),
    item("oidc", "instance", "身份提供者与群组映射", "providers mappings CODEPIER_OIDC_*", "instance", "实例管理员 / 部署管理员", "database_environment", "provider_policy", "identity-admin",
         "面板提供者走原安全入口；idp_env由环境权威管理，下次启动同步，不能从面板覆盖。", "security"),
    item("users", "instance", "实例用户权限", "active instance_admin", "instance", "实例管理员", "database", "immediate", "identity-admin",
         "用户启停和实例管理权限变更保留版本、会话撤销与最后管理员保护。", "security"),
    item("maintenance", "instance", "面板更新与运行诊断", "HUB_PANEL_UPDATE_SOCKET update diagnostics", "instance", "实例管理员 / 部署管理员", "environment", "operation_receipt", "diagnostics",
         "更新是独立维护操作，不随设置保存触发；仍在原入口确认与核对结果。"),
)


def settings_catalog():
    return {"groups": [dict(id=key, title=title) for key, title in GROUPS],
            "items": deepcopy(CATALOG)}
